# Generated by Django 2.2.2 on 2019-06-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20190626_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='image',
            field=models.ImageField(upload_to='images/uploads/'),
        ),
    ]
